super mega final actions fix

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,6 +20,9 @@ jobs:
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 9.0.x
+        
+    - name: Bandaid fix because thanks microsoft
+      run: dotnet sln ProjectPet.sln remove docker-compose.dcproj || echo "not found skipping"
 
     - name: Add NuGet source
       run: |
